wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1664650406.503239
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.13.3
      8:
      - 1
      - 3
      - 5
      10:
      - 9
epochs:
  desc: null
  value: 20
lbd:
  desc: null
  value: 0.001
lr:
  desc: null
  value: 0.001
